# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Box settings (global)
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  # NFS client configuration
  (1..1).each do |i|
config.vm.define "nfs_cln#{i}" do |nfs_cln|
  nfs_cln.vm.hostname = "nfs-cln#{i}"  # Changed from "nfs_cln-#{i}" to "nfs-cln#{i}"
  nfs_cln.vm.network "private_network", ip: "192.168.99.12#{i}"

  nfs_cln.vm.provider "virtualbox" do |vb|
    vb.name = "nfs-cln#{i}"  # This is the VM name in VirtualBox, and it's okay to have underscores here.
    vb.memory = "1024"
    vb.cpus = 1
  end

  nfs_cln.vm.provision "shell", inline: <<-SHELL
    echo "ssh-rsa YOUR PUB KEY" >> /home/vagrant/.ssh/authorized_keys
  SHELL
end
end


  # NFS server configuration
  config.vm.define "nfs_srv" do |nfs_srv|
    nfs_srv.vm.hostname = "nfs-srv"
    nfs_srv.vm.network "private_network", ip: "192.168.99.111"

    nfs_srv.vm.provider "virtualbox" do |vb|
      vb.name = "nfs_srv"
      vb.memory = "1024"
      vb.cpus = 1
    end
    nfs_srv.vm.provision "shell", inline: <<-SHELL
      echo "ssh-rsa YOUR PUB KEY" >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end