---
- hosts: all
  name: Working with Logging
  become: true

  tasks:

    - name: Check and print OS Version
      debug:
        var: ansible_os_family

  #================= Block ELK Installation =================
    - name: NGINX Debian 
      block:

        - name: Update apt cache
          apt:
            update_cache: yes
            cache_valid_time: 3600  # Updates the cache if it's older than 1 hour

        - name: Install Java OpenJDK 11
          apt:
            name: openjdk-11-jdk
            state: present
            update_cache: yes

        - name: Import Elasticsearch GPG key
          apt_key:
            url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
            state: present
    
        - name: Add Elasticsearch repository
          apt_repository:
            repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main"
            state: present
            update_cache: yes

        - name: Apt-transport-https
          apt:
             name: apt-transport-https
             state: present
    
        - name: Install Elasticsearch
          apt:
            name: elasticsearch
            state: present

        - name: Updating the config file to allow outside access
          lineinfile:
            destfile: /etc/elasticsearch/elasticsearch.yml
            regexp: 'network.host:'
            line: 'network.host: 0.0.0.0'

        - name: Updating the port in config file 
          lineinfile:
           destfile: /etc/elasticsearch/elasticsearch.yml
           regexp: 'http.port:'
           line: 'http.port: 9200'

        - name: Start and enable Elasticsearch service
          systemd:
            name: elasticsearch
            enabled: yes
            state: started
    
        - name: Install Logstash
          apt:
            name: logstash
            state: present

        - name: Configure Logstash
          template:
            src: logstash.conf.j2
            dest: /etc/logstash/conf.d/logstash.conf
          notify:
            - Restart Logstash
    
        - name: Start and enable Logstash service
          systemd:
            name: logstash
            enabled: yes
            state: started
    
        - name: Install Kibana
          apt:
            name: kibana
            state: present
          notify:
            - Reload systemctl deamon
    
        - name: Start and enable Kibana service
          systemd:
            name: kibana
            enabled: yes
            state: started

        - name: Enable X-Pack Security
          lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            line: 'xpack.security.enabled: true'
            create: yes
          notify:
            - restart elasticsearch

        - name: Set Elasticsearch built-in users' passwords
          command: /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -b
          register: es_passwords
          ignore_errors: yes
          changed_when: "'PASSWORD' in es_passwords.stdout"
        
        - name: Debug print Elasticsearch passwords
          debug:
            msg: "{{ es_passwords.stdout | default('No password output available') }}"
          when: es_passwords.stdout is defined
        
        - name: Update Kibana configuration with new password
          lineinfile:
            path: /etc/kibana/kibana.yml
            regexp: '^elasticsearch.password:'
            line: "elasticsearch.password: \"{{ (es_passwords.stdout_lines | default(['PASSWORD_NOT_SET']))[0] }}\""
            state: present
          notify:
            - Restart Kibana
          when: es_passwords.rc | default(1) == 0

        - name: Updating the config file to allow outside access
          lineinfile:
           destfile: /etc/kibana/kibana.yml
           regexp: 'server.host:'
           line: 'server.host: 0.0.0.0'

        - name: Defining server port
          lineinfile:
           destfile: /etc/kibana/kibana.yml
           regexp: 'server.port:'
           line: 'server.port: 5601'

        - name: Defining Elasticsearch URL
          lineinfile:
           destfile: /etc/kibana/kibana.yml
           regexp: 'elasticsearch.url:'
           line: 'elasticsearch.url: "http://localhost:9200"'

        - name: Copy Elasticsearch certificates to Kibana
          copy:
            src: /etc/elasticsearch/certs/
            dest: /etc/logstash
            owner: root
            group: logstash
            remote_src: yes
          notify:
            - Restart Kibana
    
        - name: Change owner of Kibana certificates
          file:
            path: /etc/kibana/certs
            owner: root
            group: kibana
            recurse: yes

        - name: Update Kibana configuration with new password
          lineinfile:
            path: /etc/kibana/kibana.yml
            regexp: '^elasticsearch.password:'
            line: "elasticsearch.password: '{{ kibana_system_password }}'"
            state: present
          notify: restart kibana


      when: inventory_hostname in groups['elk']

#  #================= Block NGINX Filebit =================
#    - name: RSYSLOG SRV Debian 
#      block:
#
#        - name: Gather the package facts
#          package_facts:
#            manager: auto
#
#        - name: Install rsyslog for Debian/Ubuntu
#          apt:
#            name: rsyslog
#            state: present
#          when: "'rsyslog' not in ansible_facts.packages"
#
#        - name: Copy rsyslog config file
#          copy:
#            src: "rsyslog.conf"
#            dest: "/etc/rsyslog.conf"
#            mode: 0644
#          notify:
#            - Restart rsyslog
#
#      when: inventory_hostname in groups['web']
#

  handlers:
    - name: Reload systemctl deamon
      become: true
      command: systemctl daemon-reload

    - name: Restart Logstash
      systemd:
        name: logstash
        state: restarted

    - name: restart elasticsearch
      systemd:
        name: elasticsearch
        state: restarted

    - name: Restart NGINX Debian
      service:
        name: nginx
        state: restarted
