---
- hosts: all
  name: Working with Logging
  become: true

  tasks:

    - name: Check and print OS Version
      debug:
        var: ansible_os_family
    
    - name: Install Packets
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - net-tools
        - curl
        - vim
        - ntp
      when: ansible_os_family == "Debian"
    
    - name: Start NTP Service
      service:
        name: ntp
        state: started
        enabled: yes
    
    - name: Copy NTP Configuration
      copy:
        src: ntp.conf
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart ntp

  #================= Block NGINX Installation =================
    - name: NGINX Debian 
      block:

        - name: Update apt cache
          apt:
            update_cache: yes
            cache_valid_time: 3600  # Updates the cache if it's older than 1 hour

        - name: Install NGINX Web Server for Debian Family
          apt:
            name: nginx
            state: latest

        - name: Start NGINX Web Server and Enabel it on boot for Debian Family
          service:
            name: nginx
            state: started
            enabled: yes

        - name: Generate nginx config file 
          template:
            src: "nginx.conf.j2"
            dest: "/etc/nginx/nginx.conf"
            mode: 0744
          notify:
            - Restart NGINX Debian

        - name: Copy files to /var/www/html
          copy:
            src: "{{ item }}"
            dest: "{{ dst_folder }}"
            mode: '0644'
          loop:
            - otus.png
            - index.html
          notify:
            - Restart NGINX Debian

      when: inventory_hostname in groups['web']

  #================= Block RSYSLOG-SRV Configuration =================
    - name: RSYSLOG SRV Debian 
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Install rsyslog for Debian/Ubuntu
          apt:
            name: rsyslog
            state: present
          when: "'rsyslog' not in ansible_facts.packages"

        - name: Copy rsyslog config file
          copy:
            src: "rsyslog.conf"
            dest: "/etc/rsyslog.conf"
            mode: 0644
          notify:
            - Restart rsyslog

      when: inventory_hostname in groups['log']

  #================= Block RSYSLOG Client Configuration =================
    - name: RSYSLOG Client Debian 
      block:

        - name: Gather the package facts
          package_facts:
            manager: auto

        - name: Install rsyslog for Debian/Ubuntu
          apt:
            name: rsyslog
            state: present
          when: "'rsyslog' not in ansible_facts.packages"

        - name: Config rsyslog file
          lineinfile:
            path: "/etc/rsyslog.conf"
            line: "*.*@@{{ log_server }}:514"
          notify:
            - Restart rsyslog

      when: inventory_hostname in groups['cln']

  handlers:
    - name: Reload systemd daemon
      command: systemctl daemon-reload
    
    - name: Restart ntp
      service:
        name: ntp
        state: restarted
    
    - name: Restart NGINX Debian
      service:
        name: nginx
        state: restarted
    
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
