---
- name: Check and print OS Version
  debug:
    var: ansible_os_family

- name: Install Packets
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - net-tools
    - curl
    - vim
    - ntp

- name: Start NTP Service
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Copy NTP Configuration
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart ntpd

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64"

- name: Create Node Exporter Group
  group:
    name: nodeusr
    state: present

- name: Create Node Exporter User
  user:
    name: nodeusr
    group: nodeusr
    system: yes
    createhome: no

- name: Copy Node Exporter Binaries
  copy:
    src: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/"
    owner: nodeusr
    group: nodeusr
    mode: 0755
    remote_src: yes
  loop:
    - node_exporter

- name: Copy Node Exporter Service Unit
  copy:
    src: "node_exporter.service"
    dest: "/etc/systemd/system/node_exporter.service"
  notify: Reload systemd daemon

- name: Start and Enable Node Exporter
  service:
    name: node_exporter
    state: started
    enabled: yes
