Vagrant.configure("2") do |config|
  # iscsi initiator 3 servers
  (1..1).each do |i|
    config.vm.define "centos-vm-#{i}" do |centos_vm|
      # Box settings
      centos_vm.vm.box = "centos/7"
      centos_vm.vm.box_check_update = false

      centos_vm.vm.hostname = "centos-vm-#{i}"
      centos_vm.vm.network "private_network", ip: "192.168.99.12#{i}"

      centos_vm.vm.provider "virtualbox" do |vb|
        vb.name = "centos-vm-#{i}"
        vb.memory = "1024"
        vb.cpus = '1'
      end

      centos_vm.vm.provision "shell", inline: <<-SHELL
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCeAb+oHb697nQo3jbOfY+fVN7ky6Hfc/x93rhUOf6Skb3JMOdCAsqNol2mVNUSWKdX+T67lD1s5G/aFPXoR9EEJz0FSTlCNg/TCLtlWu5WINRS4tPRRWQosA8uia7ni9ZcFcbrsL8VcE4S9rxtzAddsbR6KK+zSWzpHaJ/NFeBajC7/slA5ejtZJe5V1qOwwQ9MCjRi6/u+nbCBxRpEBD5svvnpqCF3l4vpRd9dRwpNtjDC2zb/hyRFBzeX076Ou6PN3NT3sy57aKEI589ZLKxTZQKw8bwPoPleCxItx3ENyD+6YBTuA+X1o05VLK9NyWa1/ZP5y0+N1Bg/0BY+2TwNkwJuEO4koZ3g/1va8yNg5xeAh0giYjoheHq8EhdD+UFDNcrarnpvmjrFM9OS/rxBdfj1i0xUTZPxVj/tNZ0wYTxpAPQhX/D5NxosfIKQsx0Ehhgita8La/GxLaEeW+yPb4hbf7hW5eXntqRch3nAATALKwLlfqctvFzyW+fkT+Tmi5Y7EI8mjcdZ0Ils0NpIvt5AJECWLiZjobBV3LWpJ0xrIiYGhx0lHYE9ekjkiHZ30NieLLBnZZbMe2BHqfNflinOH9sYfOujzfhByr6oy/YXiQdM1rrPQJ9405DrcMeLY8TRASVC120K6AiyozLlCa+Y/MhcLcVhJsY3QBCIQ== sergeynowitzki@gmail.com" >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end

  # iscsi target server configuration with two disks
  (1..1).each do |i|
    config.vm.define "ubuntu-vm-#{i}" do |ubuntu_vm|
      # Box settings
      ubuntu_vm.vm.box = "ubuntu/focal64"
      ubuntu_vm.vm.box_check_update = false

      ubuntu_vm.vm.hostname = "ubuntu-vm-#{i}"
      ubuntu_vm.vm.network "private_network", ip: "192.168.99.11#{i}"

      ubuntu_vm.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu-vm-#{i}"
        vb.memory = "1024"
        vb.cpus = '1'
      end

      ubuntu_vm.vm.provision "shell", inline: <<-SHELL
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCeAb+oHb697nQo3jbOfY+fVN7ky6Hfc/x93rhUOf6Skb3JMOdCAsqNol2mVNUSWKdX+T67lD1s5G/aFPXoR9EEJz0FSTlCNg/TCLtlWu5WINRS4tPRRWQosA8uia7ni9ZcFcbrsL8VcE4S9rxtzAddsbR6KK+zSWzpHaJ/NFeBajC7/slA5ejtZJe5V1qOwwQ9MCjRi6/u+nbCBxRpEBD5svvnpqCF3l4vpRd9dRwpNtjDC2zb/hyRFBzeX076Ou6PN3NT3sy57aKEI589ZLKxTZQKw8bwPoPleCxItx3ENyD+6YBTuA+X1o05VLK9NyWa1/ZP5y0+N1Bg/0BY+2TwNkwJuEO4koZ3g/1va8yNg5xeAh0giYjoheHq8EhdD+UFDNcrarnpvmjrFM9OS/rxBdfj1i0xUTZPxVj/tNZ0wYTxpAPQhX/D5NxosfIKQsx0Ehhgita8La/GxLaEeW+yPb4hbf7hW5eXntqRch3nAATALKwLlfqctvFzyW+fkT+Tmi5Y7EI8mjcdZ0Ils0NpIvt5AJECWLiZjobBV3LWpJ0xrIiYGhx0lHYE9ekjkiHZ30NieLLBnZZbMe2BHqfNflinOH9sYfOujzfhByr6oy/YXiQdM1rrPQJ9405DrcMeLY8TRASVC120K6AiyozLlCa+Y/MhcLcVhJsY3QBCIQ== sergeynowitzki@gmail.com" >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
end