# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = false
  config.vm.provider :virtualbox do |v|
    v.memory = 1512
    v. cpus = 2
  end


  # Define VMs with static private IP addresses.
  boxes = [
    {
      :name => "web",
      :ip => "192.168.99.111",
    },
    {
      :name => "cln",
      :ip => "192.168.99.112",
    },
    {
      :name => "log",
      :ip => "192.168.99.121",
    },
    {
      :name => "elk",
      :ip => "192.168.99.122",
    }
  ]

  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
      config.vm.provision "shell", inline: <<-SHELL
        echo "ssh-rsa YOUR PUB KEY" >> /home/vagrant/.ssh/authorized_keys
      SHELL
      if opts[:name] == boxes.last[:name]
        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "Ansible/provision.yml"
          ansible.inventory_path = "Ansible/inventories/hosts.ini"
          ansible.host_key_checking = "false"
          ansible.limit = "all"
        end
      end
    end
  end
end