version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.0.1-php8.0-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  flask:
    image: flask-app:latest
    container_name: flask
    build:
      context: ./flask-app
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./flask-app:/app # Mount the local ./flask-app directory to /app in the container
    networks:
      - app-network

  node:
    image: node-app:latest
    container_name: node
    build:
      context: ./node-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./node-app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
      - flask
      - node
    image: nginx:1.22.0-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network



volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge
