---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Updates the cache if it's older than 1 hour

- name: Install knockd
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - knockd
    - iptables-persistent
    - netfilter-persistent

- name: Start knockd and Enabel it on boot
  service:
    name: knockd
    state: started
    enabled: yes

- name: Knockd config file 
  copy:
    src: "knockd.conf"
    dest: "/etc/knockd.conf"
    mode: 0744
  notify:
    - Restart knockd

- name: Knockd autostart config file 
  copy:
    src: "knockd"
    dest: "/etc/default/knockd"
    mode: 0744
  notify:
    - Restart knockd

- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Deny new incoming SYN packets on TCP port 22 (SSH)
  iptables:
    chain: INPUT
    protocol: tcp
    in_interface: eth1
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: REJECT
    comment: Reject SSH on eth1.
        
- name: Netfilter persistent config
  command: "{{ item }}"
  loop:
    - "netfilter-persistent save"
    - "netfilter-persistent start"