---
- name: Install Borgbackup
  apt:
    name: borgbackup
    state: present

- name: Adding User with a directory
  user:
    name: borg
    comment: "Borg Backup User"
    shell: /bin/bash
    createhome: yes
    system: yes
    home: /home/borg

- name: Create a directory .ssh
  file:
    path: /home/borg/.ssh
    state: directory
    owner: borg
    group: borg
    mode: 0700

- name: Create a file .ssh/authorized_keys
  file:
    path: /home/borg/.ssh/authorized_keys
    state: touch
    owner: borg
    group: borg
    mode: 0600

- name: Change owner of a directory
  file:
    path: /var/backup
    state: directory
    owner: borg
    group: borg
    mode: 0755