# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#  (1..3).each do |i|
#  # Box settings
#  config.vm.box = "centos/7"
#  config.vm.box_check_update = false 
#
#  # iscsi initiator 3 servers 
#  config.vm.define "iscsi-int-#{i}" do |iscsi_target|
#    iscsi_target.vm.hostname = "iscsi-int-#{i}"
#    iscsi_target.vm.network "private_network", ip: "192.168.99.12#{i}"
#
#    iscsi_target.vm.provider "virtualbox" do |vb|
#      vb.name = "iscsi-int-#{i}"
#      vb.memory = "1024"
#      vb.cpus = '1'
#
#    iscsi_target.vm.provision "shell", inline: <<-SHELL
#      echo "ssh-rsa YOUR-PUB-SSH-KEY" >> /home/vagrant/.ssh/authorized_keys
#    SHELL
#    end
#  end
#end
  # iscsi target server configuration with two disks
  (1..1).each do |i|
    config.vm.define "raid-rocky" do |iscsi_target|
      config.vm.box = "generic/rocky8"
      config.vm.box_check_update = false 
      iscsi_target.vm.hostname = "raid-rocky"
      iscsi_target.vm.network "private_network", ip: "192.168.99.111"
      #config.vm.disk :disk, disk_ext: "vdi", primary: false, size: "1GB", name: "extdisk"


      iscsi_target.vm.provider "virtualbox" do |vb|
        vb.name = "raid-rocky"
        vb.memory = "4096"
        vb.cpus = '4'
      iscsi_target.vm.provision "shell", inline: <<-SHELL
        echo "your SSH-KEY.pub" >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
end
end
