---
- name: Check and print OS Version
  debug:
    var: ansible_os_family

- name: Install Packets
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - net-tools
    - curl
    - vim
    - ntp

- name: Start NTP Service
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Copy NTP Configuration
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart ntpd

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"


- name: Extract Prometheus Tarball
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/prometheus-{{ prometheus_version }}.linux-amd64"

- name: Create Prometheus Group
  group:
    name: prometheus
    state: present

- name: Create Prometheus User
  user:
    name: prometheus
    group: prometheus
    system: yes
    createhome: no

- name: Create Directories for Prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - "/etc/prometheus"
    - "/var/lib/prometheus"

- name: Copy Prometheus Binaries
  copy:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/"
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Copy Prometheus Consoles
  copy:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/etc/prometheus/"
    owner: prometheus
    group: prometheus
    mode: 0644
    remote_src: yes
  loop:
    - consoles
    - console_libraries

- name: Copy Prometheus Configuration
  template:
    src: "prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: 0644

- name: Copy Prometheus Service Unit
  copy:
    src: "prometheus.service"
    dest: "/etc/systemd/system/prometheus.service"
  notify: Reload systemd daemon

- name: Start and Enable Prometheus
  service:
    name: prometheus
    state: started
    enabled: yes
