---
- name: disable unicast RPF
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: '0'
    state: present
  notify: sysctl apply

- name: set up OSPF 
  template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: 0640
  notify: restart FRR
