---
interfaces:
  - interface: eth1
    ipv4: 10.0.10.1/30
    ospf_cost: 1000
    description: "r1-r2"
  - interface: eth2
    ipv4: 10.0.12.1/30
    ospf_cost: 100
    description: "r1-r3"
  - interface: eth3
    ipv4: 192.168.10.1/24
    ospf_cost: 100
    description: "net1"

ospf:
  - network: 10.0.10.0/30
    area: 0
  - network: 10.0.12.0/30
    area: 0
  - network: 192.168.10.0/24
    area: 0
router_id: 1.1.1.1
neighbors:
  - 10.0.10.2
  - 10.0.12.2