---
interfaces:
  - interface: eth1
    ipv4: 10.0.11.1/30
    ospf_cost: 100
    description: "r2-r3"
  - interface: eth2
    ipv4: 10.0.12.2/30
    ospf_cost: 100
    description: "r1-r3"
  - interface: eth3
    ipv4: 192.168.30.1/24
    ospf_cost: 100
    description: "net3"

ospf:
  - network: 10.0.11.0/30
    area: 0
  - network: 10.0.12.0/30
    area: 0
  - network: 192.168.30.0/24
    area: 0
router_id: 3.3.3.3
neighbors:
  - 10.0.11.2
  - 10.0.12.1