---
- name: ip forwarding enable
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present
  notify:
    - sysctl reload
  when: "inventory_hostname in groups['ROUTERS_ALL']"

- name: disable default route
  copy: 
    src: 00-installer-config.yaml
    dest: /etc/netplan/00-installer-config.yaml
    owner: root
    group: root
    mode: 0644
  notify:
    - Netplan apply
  when: (ansible_hostname != "inetRouter")

- name: Routing via netplan configuration
  template: 
    src: "50-vagrant_{{ansible_hostname}}.yaml"
    dest: /etc/netplan/50-vagrant.yaml
    owner: root
    group: root
    mode: 0644
  notify:
    - Netplan apply

- name: Set up NAT on inetRouter
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: "iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
    - { src: "iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
  notify:
    - Iptables restore 
  when: (ansible_hostname == "inetRouter")
