# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Define the main virtual machine
  config.vm.define "OpenVPNServer" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2204"
    ubuntu.vm.hostname = "OpenVPNServer"

    # Setup private network
    ubuntu.vm.network "private_network", ip: "192.168.99.111"

    # VirtualBox specific configuration
    ubuntu.vm.provider "virtualbox" do |vb|
      # Name of the VM in VirtualBox
      vb.name = "OpenVPNServer"

      # Memory and CPU
      vb.memory = "1024"
      vb.cpus = 1
    end

    ubuntu.vm.provision "shell", inline: <<-SHELL
        echo "ssh-rsa YOUR PUB KEY" >> /home/vagrant/.ssh/authorized_keys
      SHELL
  end

  (1..1).each do |i|
    config.vm.define "OpenVPNClient#{i}" do |ubuntu_vm|
      # Box settings
      ubuntu_vm.vm.box = "generic/ubuntu2204"
      ubuntu_vm.vm.box_check_update = false

      ubuntu_vm.vm.hostname = "OpenVPNClient#{i}"
      ubuntu_vm.vm.network "private_network", ip: "192.168.99.12#{i}"

      ubuntu_vm.vm.provider "virtualbox" do |vb|
        vb.name = "OpenVPNClient#{i}"
        vb.memory = "1024"
        vb.cpus = '1'
      end

      ubuntu_vm.vm.provision "shell", inline: <<-SHELL
        echo "ssh-rsa YOUR PUB KEY" >> /home/vagrant/.ssh/authorized_keys
      SHELL
#      ubuntu_vm.vm.provision "ansible" do |ansible|
#          ansible.playbook = "Ansible/provision.yml"
#          ansible.inventory_path = "Ansible/inventories/hosts.ini"
#          ansible.host_key_checking = "false"
#          ansible.limit = "all"
#      end
    end
  end
end