---
# defaults file for ansible-mdadm
#
# Define Raid Arrays to manage
mdadm_arrays:
    # Define array name
  - name: 'md127'
    # Define disk devices to assign to array
    devices:
      - '/dev/sdc'
      - '/dev/sdd'
      - '/dev/sde'
      - '/dev/sdf'
    # Define filesystem to partition array with
    filesystem: 'ext4'
    # Define the array raid level
    # 0|1|4|5|6|10
    level: '10'
    # Define mountpoint for array device
    mountpoint: "/mnt/md127"
    # Define if array should be present or absent
    state: 'absent'
    # Set mount options (optional)
    opts: 'noatime'
