MACHINES = {
  :inetRouter => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "inetRouter",
        #:public => {:ip => "10.10.10.1", :adapter => 1},
        :net => [   
                    #ip, adpter, netmask, virtualbox__intnet
                    ["192.168.255.1", 2, "255.255.255.252",  "router-net"], 
                    ["192.168.99.10", 8, "255.255.255.0"],
                ]
  },
  :inetRouter2 => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "inetRouter2",
        #:public => {:ip => "10.10.10.1", :adapter => 1},
        :net => [   
                    #ip, adpter, netmask, virtualbox__intnet
                    ["192.168.255.13", 2, "255.255.255.252",  "router-net"],
                    ["192.168.50.10", 3, "255.255.255.0"],
                    ["192.168.99.200", 8, "255.255.255.0"],
                ]
  },
  :centralRouter => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "centralRouter",
        :net => [
                   ["192.168.255.2",  2, "255.255.255.252",  "router-net"],
                   ["192.168.0.1",    3, "255.255.255.240",  "dir-net"],
                   ["192.168.0.33",   4, "255.255.255.240",  "hw-net"],
                   ["192.168.255.9",  5, "255.255.255.252",  "office1-central"],
                   ["192.168.255.5",  6, "255.255.255.252",  "office2-central"],
                   ["192.168.99.11",  7, "255.255.255.0"],
                   ["192.168.255.14", 8, "255.255.255.252",  "router-net"],
                ]
  },
  :centralServer => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "centralServer",
        :net => [
                   ["192.168.0.2",    2, "255.255.255.240",  "dir-net"],
                   ["192.168.99.12",  8, "255.255.255.0"],
                ]
  },
  :office1Router => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "office1Router",
        :net => [
                   ["192.168.255.10",  2,  "255.255.255.252",  "office1-central"],
                   ["192.168.2.1",     3,  "255.255.255.192",  "dev1-net"],
                   ["192.168.2.65",    4,  "255.255.255.192",  "test1-net"],
                   ["192.168.2.129",   5,  "255.255.255.192",  "managers-net"],
                   ["192.168.2.193",   6,  "255.255.255.192",  "office1-net"],
                   ["192.168.99.20",   8,  "255.255.255.0"],
                ]
  },
  :office1Server => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "office1Server",
        :net => [
                   ["192.168.2.130",  2,  "255.255.255.192",  "managers-net"],
                   ["192.168.99.21",  8,  "255.255.255.0"],
                ]
  },
  :office2Router => {
       :box_name => "generic/ubuntu2204",
       :vm_name => "office2Router",
       :net => [
                   ["192.168.255.6",  2,  "255.255.255.252",  "office2-central"],
                   ["192.168.1.1",    3,  "255.255.255.128",  "dev2-net"],
                   ["192.168.1.129",  4,  "255.255.255.192",  "test2-net"],
                   ["192.168.1.193",  5,  "255.255.255.192",  "office2-net"],
                   ["192.168.99.30",  8,  "255.255.255.0"],
               ]
  },
  :office2Server => {
       :box_name => "generic/ubuntu2204",
       :vm_name => "office2Server",
       :net => [
                  ["192.168.1.2",    2,  "255.255.255.128",  "dev2-net"],
                  ["192.168.99.31",  8,  "255.255.255.0"],
               ]
  }
}
Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      
      box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
       end
      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end
      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end
      box.vm.provision "shell", inline: <<-SHELL
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCeAb+oHb697nQo3jbOfY+fVN7ky6Hfc/x93rhUOf6Skb3JMOdCAsqNol2mVNUSWKdX+T67lD1s5G/aFPXoR9EEJz0FSTlCNg/TCLtlWu5WINRS4tPRRWQosA8uia7ni9ZcFcbrsL8VcE4S9rxtzAddsbR6KK+zSWzpHaJ/NFeBajC7/slA5ejtZJe5V1qOwwQ9MCjRi6/u+nbCBxRpEBD5svvnpqCF3l4vpRd9dRwpNtjDC2zb/hyRFBzeX076Ou6PN3NT3sy57aKEI589ZLKxTZQKw8bwPoPleCxItx3ENyD+6YBTuA+X1o05VLK9NyWa1/ZP5y0+N1Bg/0BY+2TwNkwJuEO4koZ3g/1va8yNg5xeAh0giYjoheHq8EhdD+UFDNcrarnpvmjrFM9OS/rxBdfj1i0xUTZPxVj/tNZ0wYTxpAPQhX/D5NxosfIKQsx0Ehhgita8La/GxLaEeW+yPb4hbf7hW5eXntqRch3nAATALKwLlfqctvFzyW+fkT+Tmi5Y7EI8mjcdZ0Ils0NpIvt5AJECWLiZjobBV3LWpJ0xrIiYGhx0lHYE9ekjkiHZ30NieLLBnZZbMe2BHqfNflinOH9sYfOujzfhByr6oy/YXiQdM1rrPQJ9405DrcMeLY8TRASVC120K6AiyozLlCa+Y/MhcLcVhJsY3QBCIQ== sergeynowitzki@gmail.com" >> /home/vagrant/.ssh/authorized_keys
      SHELL
      if boxconfig[:vm_name] == "office2Server"
        box.vm.provision "ansible" do |ansible|
          ansible.playbook = "Ansible/provision.yml"
          ansible.inventory_path = "Ansible/inventories/hosts.ini"
          ansible.host_key_checking = "false"
          ansible.limit = "all"
        end
      end
    end
  end
end
