---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.255.10/30
      routes:
        - to: 0.0.0.0/0
          via: 192.168.255.9
    eth2:
      dhcp4: no
      dhcp6: no
    eth3:
      dhcp4: no
      dhcp6: no
    eth4:
      dhcp4: no
      dhcp6: no
    eth5:
      dhcp4: no
      dhcp6: no
    eth6:
      addresses:
      - 192.168.99.20/24
  vlans:
    eth2.10:
      id: 10
      link: eth2
      dhcp4: no
    eth3.10:
      id: 10
      link: eth3
      dhcp4: no
    eth4.20:
      id: 20
      link: eth4
      dhcp4: no
    eth5.20:
      id: 20
      link: eth5
      dhcp4: no
  bridges:
    br1:
      interfaces:
        - eth2.10
        - eth3.10
      dhcp4: no
      addresses:
        - 192.168.10.1/24
      parameters:
        stp: false
        forward-delay: 0
    br2:
      interfaces:
        - eth4.20
        - eth5.20
      dhcp4: no
      addresses:
        - 192.168.20.1/24
      parameters:
        stp: false
        forward-delay: 0
