---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      dhcp4: no
    eth2:
      dhcp4: no
      addresses:
      - 192.168.99.21/24
  vlans:
    eth1.10:
      id: 10
      link: eth1
      addresses:
        - 192.168.10.10/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.10.1
